### ISSUE TITLE
Add bus details to student and teacher creation

### ISSUE THREAD

**Issue by kumaresan-subramani** [kd-school-erp/erp-api#171]
## Update student CRUD API

- POST - include bus_id fields
- update store procedure 
- As like adding class to `studentClassAllocation` table, need to update `StudentBusAllocation`

![image](https://user-images.githubusercontent.com/36756050/232305523-aa8cd8e6-8b6c-467c-8d03-7518e7ed65fb.png)

## Update teacherCRUD API

- POST - include bus_id fields
- update store procedure 
- As like adding class to `Classteacher` table, need to update `TeacherBusAllocation`

![image](https://user-images.githubusercontent.com/36756050/232305655-b45bda45-4e69-406f-9a69-d27fdd4a1eef.png)

**Comment by kural214** [comment]
Student POST API mock data:

[{
    "school_id": 11,
    "roll_no": 10000,
    "first_name": "fury1",
    "last_name": "fury1",
    "surname": "fury1",
    "username": "fury1",
    "password": "fury1",
    "dob": "2023-04-14",
    "gender": "male",
    "phone_number": "3515311113",
    "alternate_number": "5315313515",
    "image": "",
    "hostel": "Yes",
    "rigistration_date": "2023-04-14",
    "blood_group": "B",
    "address": "Karur",
    "district": "Bamboo Flat",
    "state": "Andaman and Nicobar Islands",
    "country": "India",
    "class_name": "STD-1",
    "class_id": 18,
    "bus_id": 7
}]

Student PUT API mock data:

{
    "id": 46,
    "school_id": 11,
    "roll_no": 10000,
    "first_name": "fury11",
    "last_name": "fury1",
    "surname": "fury1",
    "username": "fury1",
    "password": "fury1",
    "dob": "2023-04-14",
    "gender": "male",
    "phone_number": "3515311113",
    "alternate_number": "5315313515",
    "image": "",
    "hostel": "Yes",
    "rigistration_date": "2023-04-14",
    "blood_group": "B",
    "address": "Karur",
    "district": "Bamboo Flat",
    "state": "Andaman and Nicobar Islands",
    "country": "India",
    "class_name": "STD-1",
    "class_id": 18,
    "created_by": 11
}

**Comment by kural214** [comment]
Teacher POST API mock data:

[{
    "school_id": 11,
    "name": "max1",
    "image": null,
    "email_id": "max1@gmail.com",
    "phone_number": "3513513513",
    "gender": "male",
    "username": "max1",
    "password": "max1",
    "department_id": 41,
    "subject_id": 35,
    "education": "max",
    "experience": "",
    "designation": "max",
    "about_description": "",
    "joining_date": "2023-04-14",
    "address": "Karur",
    "district": "Bamboo Flat",
    "state": "Andaman and Nicobar Islands",
    "country": "India",
    "pincode": "131132",
    "class_id": 18,
    "class_name": "STD-1",
    "subject_name": "Tamil",
    "created_by": 11,
    "bus_id": 7
}]

Teacher PUT API mock data:

{
    "id": 84,
    "school_id": 11,
    "name": "max1",
    "image": null,
    "email_id": "max1@gmail.com",
    "phone_number": "3513513513",
    "gender": "male",
    "username": "max1",
    "password": "max1",
    "department_id": 41,
    "subject_id": 35,
    "education": "max",
    "experience": "",
    "designation": "max",
    "about_description": "",
    "joining_date": "2023-04-14",
    "address": "Karur",
    "district": "Bamboo Flat",
    "state": "Andaman and Nicobar Islands",
    "country": "India",
    "pincode": "131132",
    "class_id": 18,
    "class_name": "STD-1",
    "subject_name": "Tamil",
    "created_by": 11,
    "bus_id": 5
}
